[mypy]
python_version = 3.11
warn_unused_configs = True

[mypy-firmware.st7735]
ignore_errors = True

[mypy-firmware.print_rom]
ignore_errors = True

[mypy-firmware.board_pico]
ignore_errors = True

[mypy-firmware.screen_tft]
ignore_errors = True

[mypy-firmware.config_pico]
ignore_errors = True
