name: Check All Temperatures

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  check_temperatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          path: main
      - uses: actions/checkout@v6
        with:
          ref: sensor_data
          path: sensor_data
      - name: Sync Sensor Data
        run: mkdir -p main/dashboard/_posts && rsync -a --delete sensor_data/data/ main/dashboard/_posts/
      - name: Check Temperatures
        working-directory: main
        run: python scripts/check_all_temperatures.py
