name: Check Temperature Sensor Just Committed

on: [push]

jobs:
  check_temperatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2  # v4
#        with:
#          fetch-depth: 1
      - name: Check Temperatures
        run: python scripts/check_temperatures.py ${{ github.sha }}
        shell: bash
