name: Check All Temperatures On Demand

on: workflow_dispatch

jobs:
  check_temperatures:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2
      - name: Check Temperatures
        run: python scripts/check_all_temperatures.py
        shell: bash
