name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      build_name:
        description: "Custom build name (e.g., dev-test, staging)"
        required: true
        default: "manual-build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi build-essential cmake python3 python3-pip texlive-latex-recommended latexmk

#      - name: Clone MicroPython
#        run: |
#          git clone https://github.com/micropython/micropython.git
#          cd micropython
#          git submodule update --init --recursive
#
#      - name: Copy application modules into rp2 port
#        run: |
#          cp firmware/main.py micropython/ports/rp2/modules/
#          mkdir micropython/ports/rp2/modules/firmware
#          cp firmware/board_base.py micropython/ports/rp2/modules/firmware
#          cp firmware/board_pico.py micropython/ports/rp2/modules/firmware
#          cp firmware/config_base.py micropython/ports/rp2/modules/firmware
#          cp firmware/config_data.py micropython/ports/rp2/modules/firmware
#          cp firmware/config_pico.py micropython/ports/rp2/modules/firmware
#          cp firmware/font.py micropython/ports/rp2/modules/firmware
#          cp firmware/screen_base.py micropython/ports/rp2/modules/firmware
#          cp firmware/screen_tft.py micropython/ports/rp2/modules/firmware
#          cp firmware/sensing.py micropython/ports/rp2/modules/firmware
#          cp firmware/st7735.py micropython/ports/rp2/modules/firmware
#          cp firmware/__init__.py micropython/ports/rp2/modules/firmware
#
#      - name: Build Pico W firmware
#        run: |
#          cd micropython/ports/rp2
#          make BOARD=RPI_PICO_W -j 3
#
#      - name: Rename firmware
#        run: |
#          mkdir output
#          cp micropython/ports/rp2/build-RPI_PICO_W/firmware.uf2 output/pico-w-firmware.uf2
#
#      - name: Upload firmware as Actions artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: pico-w-firmware
#          path: output/pico-w-firmware.uf2
#
#      - name: Upload firmware to release
#        if: github.event_name == 'release'
#        uses: softprops/action-gh-release@v2
#        with:
#          files: output/pico-w-firmware.uf2

      - name: Build instruction manual
        working-directory: docs
        run: |
          pip install sphinx
          make latexpdf

      - name: Package instruction manual
        run: cp docs/_build/latex/assembly.pdf output/AssemblyInstructions.pdf

      - name: Upload instruction manual as Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: instruction-manual
          path: output/AssemblyInstructions.pdf

      - name: Upload instructions to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: output/AssemblyInstructions.pdf

      - name: Upload 3D models as Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3d-models
          path: model/*

      - name: Upload 3D models to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: model/*
